import { ContentItem } from '@/types';

export const INITIAL_CONTENT_ITEMS: ContentItem[] = [
  // 1. AI & Technology
  {
    id: 'ai-next-frontier-2025',
    title: 'The Rise of Autonomous Agentic Workflows in Production Software',
    description: 'How multi-agent orchestration, tool-calling LLMs, and real-time reasoning loops are transforming modern enterprise software engineering.',
    category: 'ai',
    sourceType: 'news',
    sourceName: 'DeepMind Insights',
    author: 'Dr. Demis Hassabis',
    authorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80',
    authorHandle: '@demishassabis',
    url: 'https://deepmind.google/discover/blog/',
    imageUrl: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800&auto=format&fit=crop&q=80',
    publishedAt: '10 minutes ago',
    readTime: '6 min read',
    rating: 4.9,
    likes: 1420,
    shares: 480,
    commentsCount: 94,
    mediaType: 'article',
    tags: ['AI', 'Agentic Workflows', 'Deep Learning', 'LLMs'],
    isTrending: true,
    trendingRank: 1,
    isBreaking: true,
    summary: 'A deep exploration into autonomous agents that self-correct, plan complex hierarchies, and execute multi-step workflows with zero human intervention.',
  },
  {
    id: 'tech-quantum-computing-breakthrough',
    title: 'Fault-Tolerant Quantum Processors Hit 1,000 Logical Qubits',
    description: 'Researchers achieve unprecedented coherence time and error correction thresholds, bringing quantum supremacy to practical molecular chemistry.',
    category: 'technology',
    sourceType: 'news',
    sourceName: 'MIT Technology Review',
    author: 'Elena Rostova',
    authorAvatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=100&auto=format&fit=crop&q=80',
    authorHandle: '@erostova_mit',
    url: 'https://technologyreview.com',
    imageUrl: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=800&auto=format&fit=crop&q=80',
    publishedAt: '25 minutes ago',
    readTime: '4 min read',
    rating: 4.8,
    likes: 890,
    shares: 310,
    commentsCount: 52,
    mediaType: 'article',
    tags: ['Quantum', 'Computing', 'Physics', 'Hardware'],
    isTrending: true,
    trendingRank: 3,
    summary: 'Key milestones achieved in error suppression allows quantum algorithms to simulate complex bio-molecular pathways for the first time.',
  },

  // 2. Recommendations (Movies & Media)
  {
    id: 'movie-interstellar-odyssey-2025',
    title: 'Cosmic Horizons: The Edge of Singularity (2025)',
    description: 'Directed by Denis Villeneuve • An astronaut crew travels through an exotic matter wormhole to investigate a distress signal from humanity’s first interstellar ark.',
    category: 'entertainment',
    sourceType: 'recommendation',
    sourceName: 'TMDB Spotlight',
    author: 'TMDB Editor Picks',
    authorAvatar: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=100&auto=format&fit=crop&q=80',
    url: 'https://themoviedb.org',
    imageUrl: 'https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?w=800&auto=format&fit=crop&q=80',
    publishedAt: '1 hour ago',
    readTime: '2h 45m runtime',
    rating: 9.3,
    likes: 3200,
    shares: 1200,
    commentsCount: 240,
    mediaType: 'video',
    mediaUrl: 'https://www.youtube.com/watch?v=zSWdZVtXT7E',
    tags: ['Sci-Fi', 'Cinema', 'IMAX', 'Must Watch', 'Space'],
    isTrending: true,
    trendingRank: 2,
    summary: 'A breathtaking cinematic masterpiece combining hard scientific accuracy with philosophical questions on human destiny.',
  },
  {
    id: 'podcast-lex-tech-future',
    title: 'The Future of Neural Interfaces & Human Longevity',
    description: 'Lex Fridman & Neuralink Lead Neuroengineers discuss direct optical brain-computer interfaces, memory augmentations, and bio-telepathy.',
    category: 'technology',
    sourceType: 'podcast',
    sourceName: 'Spotify Podcast',
    author: 'Lex Fridman',
    authorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80',
    authorHandle: '@lexfridman',
    url: 'https://spotify.com',
    imageUrl: 'https://images.unsplash.com/photo-1478737270239-2f02b77fc618?w=800&auto=format&fit=crop&q=80',
    publishedAt: '2 hours ago',
    readTime: '3h 12m listen',
    rating: 4.9,
    likes: 2150,
    shares: 640,
    commentsCount: 188,
    mediaType: 'audio',
    mediaUrl: 'https://interactive-examples.mdn.mozilla.net/media/cc0-audio/t-rex-roar.mp3',
    tags: ['Podcast', 'BCI', 'Neuralink', 'Future'],
    summary: 'An insightful 3-hour discussion on biological constraints, synthetic synapse scaling, and ethics of human cognitive enhancement.',
  },

  // 3. Social Media Buzz
  {
    id: 'social-post-sam-altman-agi',
    title: 'Sam Altman on Recursive Self-Improving Architecture',
    description: '“The speed at which synthetic reasoning and autonomous coding have progressed in the last 6 months has surpassed all 2020 forecasts. The next era is self-orchestrating teams of AI engineers.”',
    category: 'ai',
    sourceType: 'social',
    sourceName: 'X / Twitter',
    author: 'Sam Altman',
    authorAvatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=100&auto=format&fit=crop&q=80',
    authorHandle: '@sama',
    url: 'https://x.com/sama',
    imageUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&auto=format&fit=crop&q=80',
    publishedAt: '35 minutes ago',
    likes: 18450,
    shares: 5210,
    commentsCount: 1420,
    mediaType: 'image',
    tags: ['AI', 'TechTwitter', 'AGI', 'FutureOfWork'],
    isTrending: true,
    trendingRank: 4,
  },
  {
    id: 'social-post-marques-m4-ultra',
    title: 'The Mac Studio M4 Ultra is ridiculous overkill in the best way possible',
    description: 'Rendering 8K ProRes RAW in real-time with 32 neural engine instances running locally without the fans spinning above 800 RPM. Full review dropping tomorrow!',
    category: 'technology',
    sourceType: 'social',
    sourceName: 'Threads / Instagram',
    author: 'Marques Brownlee',
    authorAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&auto=format&fit=crop&q=80',
    authorHandle: '@mkbhd',
    url: 'https://instagram.com/mkbhd',
    imageUrl: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800&auto=format&fit=crop&q=80',
    publishedAt: '3 hours ago',
    likes: 42300,
    shares: 8900,
    commentsCount: 3100,
    mediaType: 'image',
    tags: ['Apple', 'Hardware', 'Review', 'M4Ultra'],
    isTrending: false,
  },

  // 4. Finance & Crypto
  {
    id: 'finance-global-markets-defi',
    title: 'Global Central Banks Pilot Real-Time Cross-Border Settlement On Public Blockchains',
    description: 'Major institutional liquidity providers switch to sub-second decentralized settlement rails, eliminating 48-hour clearing windows.',
    category: 'finance',
    sourceType: 'news',
    sourceName: 'Bloomberg Financial',
    author: 'Marcus Sterling',
    authorAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&auto=format&fit=crop&q=80',
    authorHandle: '@msterling_markets',
    url: 'https://bloomberg.com',
    imageUrl: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=800&auto=format&fit=crop&q=80',
    publishedAt: '4 hours ago',
    readTime: '5 min read',
    rating: 4.7,
    likes: 950,
    shares: 340,
    commentsCount: 82,
    mediaType: 'article',
    tags: ['Finance', 'Markets', 'DeFi', 'Economy', 'FinTech'],
    summary: 'The shift marks a historic transformation in global capital efficiency and liquidity velocity across Asian and European markets.',
  },

  // 5. Sports & Fitness
  {
    id: 'sports-champions-league-thriller',
    title: 'Champions League Quarterfinal: 94th Minute Overhead Bicycle Kick Wins Epic Tie',
    description: 'A miraculous last-gasp winner under the lights at Santiago Bernabéu seals a historic 4-3 comeback victory in front of 85,000 roaring fans.',
    category: 'sports',
    sourceType: 'news',
    sourceName: 'The Athletic / ESPN',
    author: 'Julian Barnes',
    authorAvatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=100&auto=format&fit=crop&q=80',
    authorHandle: '@jbarnes_football',
    url: 'https://theathletic.com',
    imageUrl: 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?w=800&auto=format&fit=crop&q=80',
    publishedAt: '5 hours ago',
    readTime: '3 min read',
    rating: 4.9,
    likes: 6700,
    shares: 2100,
    commentsCount: 650,
    mediaType: 'article',
    tags: ['Football', 'ChampionsLeague', 'Sports', 'Highlights'],
    isTrending: true,
    trendingRank: 5,
  },

  // 6. Science & Space
  {
    id: 'science-james-webb-exoplanet-atmosphere',
    title: 'James Webb Telescope Detects Water Vapor & Biological Markers on Exoplanet K2-18b',
    description: 'Spectroscopic analysis reveals dimethyl sulfide (DMS) signatures in the atmosphere of a habitable-zone sub-Neptune exoplanet 120 light-years away.',
    category: 'science',
    sourceType: 'news',
    sourceName: 'NASA Astrobiology & Nature',
    author: 'Dr. Sarah Lin',
    authorAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100&auto=format&fit=crop&q=80',
    authorHandle: '@sarahlin_astro',
    url: 'https://nasa.gov',
    imageUrl: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800&auto=format&fit=crop&q=80',
    publishedAt: '6 hours ago',
    readTime: '7 min read',
    rating: 5.0,
    likes: 12400,
    shares: 4800,
    commentsCount: 920,
    mediaType: 'article',
    tags: ['Space', 'JWST', 'Exoplanets', 'Astrobiology', 'Science'],
    isTrending: true,
  },

  // 7. Health & Wellness
  {
    id: 'health-longevity-cellular-reprogramming',
    title: 'Yamanaka Factors Reversal: Cellular Age Regression Demonstrated in Human Trial',
    description: 'Epigenetic clocks reset by an average of 7.4 biological years across vital organ tissue using targeted mRNA transient delivery.',
    category: 'health',
    sourceType: 'news',
    sourceName: 'Cell / Harvard Medical',
    author: 'Dr. David Sinclair Team',
    authorAvatar: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=100&auto=format&fit=crop&q=80',
    authorHandle: '@harvardmed',
    url: 'https://hms.harvard.edu',
    imageUrl: 'https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?w=800&auto=format&fit=crop&q=80',
    publishedAt: '7 hours ago',
    readTime: '6 min read',
    rating: 4.8,
    likes: 3800,
    shares: 1450,
    commentsCount: 310,
    mediaType: 'article',
    tags: ['Longevity', 'Medicine', 'BioTech', 'Health', 'Genetics'],
  },

  // 8. Entertainment & Music Recommendation
  {
    id: 'recommendation-synthwave-odyssey',
    title: 'Neon Odyssey (Synthwave / Cyberpunk Ambient OST)',
    description: 'Spotify Weekly Discovery • Immerse yourself in 80 minutes of analog synthesizers, tape saturation, and neo-Tokyo night drive vibes.',
    category: 'entertainment',
    sourceType: 'recommendation',
    sourceName: 'Spotify Curated',
    author: 'Kavinsky & Gunship',
    authorAvatar: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=100&auto=format&fit=crop&q=80',
    url: 'https://spotify.com',
    imageUrl: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800&auto=format&fit=crop&q=80',
    publishedAt: '8 hours ago',
    readTime: '1h 20m album',
    rating: 4.9,
    likes: 5400,
    shares: 1800,
    commentsCount: 210,
    mediaType: 'audio',
    mediaUrl: 'https://interactive-examples.mdn.mozilla.net/media/cc0-audio/t-rex-roar.mp3',
    tags: ['Music', 'Synthwave', 'Focus', 'Coding Beats', 'Spotify'],
  },

  // 9. Technology & Open Source
  {
    id: 'tech-rust-linux-kernel-6-15',
    title: 'Rust in the Linux Kernel: 100% of New Drivers Written in Memory-Safe Rust',
    description: 'Linus Torvalds and core maintainers celebrate milestone as zero memory-safety CVEs are reported in newly integrated subsystems.',
    category: 'technology',
    sourceType: 'news',
    sourceName: 'LWN.net / Hacker News',
    author: 'Kees Cook',
    authorAvatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=100&auto=format&fit=crop&q=80',
    authorHandle: '@keescook',
    url: 'https://lwn.net',
    imageUrl: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800&auto=format&fit=crop&q=80',
    publishedAt: '9 hours ago',
    readTime: '5 min read',
    rating: 4.9,
    likes: 4100,
    shares: 1600,
    commentsCount: 480,
    mediaType: 'article',
    tags: ['Rust', 'Linux', 'OpenSource', 'Security', 'DevOps'],
  },

  // 10. AI / Robotics
  {
    id: 'ai-humanoid-robotics-general-purpose',
    title: 'General-Purpose Humanoid Robots Begin Autonomous Factory Deployments',
    description: 'Equipped with end-to-end vision-language-action foundation models, robots learn complex assembly tasks from single video demonstrations.',
    category: 'ai',
    sourceType: 'news',
    sourceName: 'Robotics Today / TechCrunch',
    author: 'Bret Taylor',
    authorAvatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=100&auto=format&fit=crop&q=80',
    url: 'https://techcrunch.com',
    imageUrl: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=800&auto=format&fit=crop&q=80',
    publishedAt: '11 hours ago',
    readTime: '4 min read',
    rating: 4.8,
    likes: 3100,
    shares: 980,
    commentsCount: 190,
    mediaType: 'article',
    tags: ['Robotics', 'AI', 'Automation', 'Future'],
  },

  // 11. Social / Design
  {
    id: 'social-design-tokens-2025',
    title: 'Micro-Interactions and Spatial Glassmorphism in Modern Web UI',
    description: 'A breakdown of high-performance physics-based animations, dynamic contrast calculations, and CSS anchor positioning that delight users.',
    category: 'technology',
    sourceType: 'social',
    sourceName: 'Dribbble / Figma Community',
    author: 'Elena Vance',
    authorAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=100&auto=format&fit=crop&q=80',
    authorHandle: '@elena_ui',
    url: 'https://dribbble.com',
    imageUrl: 'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?w=800&auto=format&fit=crop&q=80',
    publishedAt: '12 hours ago',
    likes: 8900,
    shares: 2400,
    commentsCount: 340,
    mediaType: 'image',
    tags: ['UI/UX', 'Figma', 'CSS', 'Frontend', 'Design'],
  },

  // 12. Finance / Startups
  {
    id: 'finance-seed-rounds-ai-agents',
    title: 'AI Native Software Startups Reach $10M ARR in Record 11 Months',
    description: 'Lean teams of 4 engineers leverage agentic coding architectures to ship global scale platforms with 90% gross margins.',
    category: 'finance',
    sourceType: 'news',
    sourceName: 'Financial Times / YC Gazette',
    author: 'Garry Tan',
    authorAvatar: 'https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?w=100&auto=format&fit=crop&q=80',
    authorHandle: '@garrytan',
    url: 'https://ft.com',
    imageUrl: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&auto=format&fit=crop&q=80',
    publishedAt: '14 hours ago',
    readTime: '5 min read',
    rating: 4.7,
    likes: 1980,
    shares: 720,
    commentsCount: 164,
    mediaType: 'article',
    tags: ['Startups', 'VentureCapital', 'SaaS', 'Finance'],
  }
];

export const BREAKING_LIVE_POOL: ContentItem[] = [
  {
    id: 'live-breaking-starship-mars-orbit',
    title: 'BREAKING: SpaceX Starship Successfully Enters Mars Transfer Orbit',
    description: 'Telemetry confirms orbital injection burn completed flawlessly. Uncrewed cargo vessel is on 6-month trajectory to the Red Planet.',
    category: 'science',
    sourceType: 'news',
    sourceName: 'SpaceX Mission Control',
    author: 'Mission Director',
    authorAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=100&auto=format&fit=crop&q=80',
    authorHandle: '@spacex',
    url: 'https://spacex.com',
    imageUrl: 'https://images.unsplash.com/photo-1541185933-ef5d8ed016c2?w=800&auto=format&fit=crop&q=80',
    publishedAt: 'Just now',
    readTime: '2 min read',
    rating: 5.0,
    likes: 9800,
    shares: 4200,
    commentsCount: 880,
    mediaType: 'article',
    tags: ['SpaceX', 'Mars', 'Starship', 'BreakingNews'],
    isTrending: true,
    isBreaking: true,
  },
  {
    id: 'live-social-andrej-karpathy-microgpt',
    title: '“You can now train a 1B parameter reasoning model on a single consumer GPU in 4 hours”',
    description: 'Released open-weights microGPT-v3 with bit-level quantization and tree-search verification. Repo link in bio!',
    category: 'ai',
    sourceType: 'social',
    sourceName: 'X / Twitter',
    author: 'Andrej Karpathy',
    authorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80',
    authorHandle: '@karpathy',
    url: 'https://x.com/karpathy',
    imageUrl: 'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=800&auto=format&fit=crop&q=80',
    publishedAt: '1 minute ago',
    likes: 12500,
    shares: 3800,
    commentsCount: 620,
    mediaType: 'image',
    tags: ['AI', 'OpenSource', 'MachineLearning', 'PyTorch'],
    isTrending: true,
    isBreaking: false,
  },
  {
    id: 'live-movie-inception-remaster',
    title: 'Inception 15th Anniversary 8K IMAX Re-Release Announced',
    description: 'Christopher Nolan personally oversees full 70mm film restoration with uncompressed Dolby Atmos soundtrack and 30 mins of never-before-seen footage.',
    category: 'entertainment',
    sourceType: 'recommendation',
    sourceName: 'Warner Bros / TMDB',
    author: 'Cinema News',
    authorAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&auto=format&fit=crop&q=80',
    url: 'https://themoviedb.org',
    imageUrl: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=800&auto=format&fit=crop&q=80',
    publishedAt: '2 minutes ago',
    readTime: '2h 28m runtime',
    rating: 9.1,
    likes: 4800,
    shares: 1900,
    commentsCount: 410,
    mediaType: 'video',
    mediaUrl: 'https://www.youtube.com/watch?v=YoHD9XEInc0',
    tags: ['Cinema', 'IMAX', 'Nolan', 'SciFi'],
    isTrending: true,
  },
  {
    id: 'live-finance-fed-rate-cut',
    title: 'Federal Reserve Announces Historic 50bps Interest Rate Cut',
    description: 'Chairman signals sustained disinflation and strong economic resilience. Tech and green energy equities rally 4.2% in after-hours trading.',
    category: 'finance',
    sourceType: 'news',
    sourceName: 'Wall Street Journal',
    author: 'Victoria Sterling',
    authorAvatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=100&auto=format&fit=crop&q=80',
    authorHandle: '@vsterling_wsj',
    url: 'https://wsj.com',
    imageUrl: 'https://images.unsplash.com/photo-1590283603385-17ffb3a7f29f?w=800&auto=format&fit=crop&q=80',
    publishedAt: '3 minutes ago',
    readTime: '4 min read',
    rating: 4.8,
    likes: 2700,
    shares: 890,
    commentsCount: 310,
    mediaType: 'article',
    tags: ['Economy', 'Fed', 'StockMarket', 'Finance'],
    isBreaking: true,
  }
];

export const DEMO_PROFILES = [
  {
    id: 'user-pushpendar',
    name: 'Pushpendar Singh',
    email: 'pushpendar.singh@example.com',
    avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80',
    bio: 'Software Development Engineer | Passionate about Frontend Architecture, React, Next.js & Agentic Systems',
    role: 'SDE Intern / Frontend Specialist',
    isAuthenticated: true,
    joinedDate: 'October 2026',
  },
  {
    id: 'user-sarah-trader',
    name: 'Sarah Jenkins',
    email: 'sarah.j@hedgefund.io',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    bio: 'Quantitative Analyst & Macro Trader. Following real-time finance, tech, and crypto derivatives.',
    role: 'Financial Analyst',
    isAuthenticated: true,
    joinedDate: 'August 2026',
  },
  {
    id: 'user-elena-designer',
    name: 'Elena Rostova',
    email: 'elena@studio-vance.design',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    bio: 'Senior Product Designer & Creative Technologist. Enthusiast for micro-interactions and generative visual arts.',
    role: 'Product Designer',
    isAuthenticated: true,
    joinedDate: 'May 2026',
  }
];
